In [1]:
import pandas as pd

In [2]:
# Load the dataset
df = pd.read_csv('Olist_Sample_Exploration.csv')

In [3]:
# showing first 5 rows
print("--- First 5 Rows ---")
display(df.head())

--- First 5 Rows ---

,order_id,order_purchase_timestamp,customer_city,customer_state,product_price,shipping_cost,product_category_name
0,00010242fe8c5a6d1ba2dd792cb16214,2017-09-13 08:59:02+00,campos dos goytacazes,RJ,58.90,13.29,cool_stuff
1,00018f77f2f0320c557190d7a144bdd3,2017-04-26 10:53:06+00,santa fe do sul,SP,239.90,19.93,pet_shop
2,000229ec398224ef6ca0657da4fc703e,2018-01-14 14:33:31+00,para de minas,MG,199.00,17.87,moveis_decoracao
3,00024acbcdf0a6daa1e931b038114c75,2018-08-08 10:00:35+00,atibaia,SP,12.99,12.79,perfumaria
4,00042b26cf59d7ce69dfabb4e55b4fd9,2017-02-04 13:57:51+00,varzea paulista,SP,199.90,18.14,ferramentas_jardim

In [4]:
# Check for missing values and data types
print("\n--- Dataset Info ---")
df.info()

--- Dataset Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   order_id                  5000 non-null   object
 1   order_purchase_timestamp  5000 non-null   object
 2   customer_city             5000 non-null   object
 3   customer_state            5000 non-null   object
 4   product_price             5000 non-null   float64
 5   shipping_cost             5000 non-null   float64
 6   product_category_name     4936 non-null   object
dtypes: float64(2), object(5)
memory usage: 273.6+ KB

In [5]:
# Convert the purchase timestamp to a proper Datetime format
df['order_purchase_timestamp'] = pd.to_datetime(df['order_purchase_timestamp'])

In [6]:
# Handle missing product categories by labeling them as 'Unknown'
df['product_category_name'] = df['product_category_name'].fillna('Unknown')

In [7]:
# Check for any duplicate rows and drop them
df = df.drop_duplicates()

In [8]:
# Verify the cleaning worked
print("--- Cleaned Dataset Info ---")
df.info()

--- Cleaned Dataset Info ---
<class 'pandas.core.frame.DataFrame'>
Index: 4522 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   order_id                  4522 non-null   object
 1   order_purchase_timestamp  4522 non-null   datetime64[ns, UTC]
 2   customer_city             4522 non-null   object
 3   customer_state            4522 non-null   object
 4   product_price             4522 non-null   float64
 5   shipping_cost             4522 non-null   float64
 6   product_category_name     4522 non-null   object
dtypes: datetime64[ns, UTC](1), float64(2), object(4)
memory usage: 282.6+ KB

In [9]:
# Calculate the total value of each item
df['total_item_value'] = df['product_price'] + df['shipping_cost']

In [10]:
# Group the data by State to calculate Frequency (orders) and Monetary (revenue)
state_segmentation = df.groupby('customer_state').agg(
    total_orders=('order_id', 'nunique'),
    total_revenue=('total_item_value', 'sum'),
    avg_order_value=('total_item_value', 'mean')
).reset_index()

In [11]:
# Sort by total revenue to find our "Champion" states
state_segmentation = state_segmentation.sort_values(by='total_revenue', ascending=False)

In [12]:
# Round the numbers to 2 decimal places for cleaner reading
state_segmentation['total_revenue'] = state_segmentation['total_revenue'].round(2)
state_segmentation['avg_order_value'] = state_segmentation['avg_order_value'].round(2)

In [13]:
# Display the Top 10 States
print("--- Top 10 Champion States by Revenue ---")
display(state_segmentation.head(10))

--- Top 10 Champion States by Revenue ---

   customer_state  total_orders  total_revenue  avg_order_value
25             SP          1828      239587.72           126.97
18             RJ           596       88942.24           144.62
10             MG           497       82177.98           161.13
17             PR           200       33783.72           167.25
22             RS           238       32853.55           135.20
23             SC           158       22170.80           133.56
4              BA           151       20671.60           135.11
6              DF           113       17483.13           146.92
8              GO            85       13975.43           158.81
15             PE            68       13709.30           195.85

In [14]:
# Export the cleaned master dataset to a new CSV
df.to_csv('Cleaned_Olist_Sample.csv', index=False)
print("Cleaned dataset successfully exported!")

Cleaned dataset successfully exported!